### ISSUE TITLE
Can devtools-timeline-model work on a smaller set of trace events?

### ISSUE THREAD

**Issue by hrgui** [paulirish/devtools-timeline-model#20]
I have a list of events, but I had already filtered it down to just 'TimerInstall, TimerFire, TimerRemove, XHRLoad, EvaluateScript, ResourceSendRequest', because i'm only interested with those events in my data analysis.

```javascript
> var model = new DevtoolsTimelineModel(events)
TracingStartedInPage event not found.
```

===
Update 12/7 11:23 AM

It looks like I needed "disabled-by-default-devtools.timeline" and __metadata trace entries, but when I call

```javascript
let model = new DevtoolsTimelineModel(entries);
let timelineModel = model.timelineModel();

let networkRequests = timelineModel.networkRequests();
```

The networkRequests do show up, but the endTime is infinity. Will look into it some more. 

===
Update 12/7 11:37 AM

Looks like I needed these extra events after looking into how networkRequests are made in devtools-frontend:

```
       ['ResourceReceiveResponse',
        'ResourceReceivedData',
        'ResourceFinish',
        'ResourceSendRequest']
```

**Comment by paulirish** [comment]
:D Yeah i think you're answering your own question.

I personally wouldnt filter it manually before feeding to d-t-m. I would just change the trace categories I collect.

**Comment by hrgui** [comment]
I see.

Originally I did that - but I ran into memory issues when passing it into d-t-m because it was too large. 

I finally got all the data I needed today after reading the devtools-frontend code, so I'm closing this.
