### ISSUE TITLE
NodeJS issues

### ISSUE THREAD

**Issue by Captainkjdh** [paulirish/devtools-timeline-model#3]
Hey there, just tried running this code through the node.js module. However, it's throwing an issue on `require('./lib/api-stubs')`. Upon further inspection I noticed this file isn't included in the module at all. Might this need to be included?

**Comment by paulirish** [comment]
hmm.. afaik, it should have been in the module as of 1.0.3

anyway. the latest should be all good. thanks for reporting!

**Comment by paulirish** [comment]
Sorry. I closed this too early.

I had a problem in the package.json. It's fixed finally.

**Comment by Captainkjdh** [comment]
Great, thanks Paul! :+1:
